const contenedor = document.getElementById('container');
const segundoItem = document.querySelectorAll('.second');
const tercerOl = document.querySelector('ol .third');
console.log(tercerOl.textContent); 
contenedor.textContent = 'Hello!';
const footerDiv = document.querySelector('.footer');
footerDiv.classList.add('main');
footerDiv.classList.remove('main');
const nuevoLi = document.createElement('li');
nuevoLi.textContent = 'four';
const ulElement = document.querySelector('ul');
ulElement.appendChild(nuevoLi);